name: MacOS

on:
  push:
    branches:
      - develop
      - master
      - release/*
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.compiler.name }} ${{ matrix.build_type }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, macos-12]
        build_type: [Release, Debug]
        compiler: [
          {name: GCC 9, cc: gcc-9, cxx: g++-9, brew_ver: gcc@9},
          {name: GCC 10, cc: gcc-10, cxx: g++-10, brew_ver: gcc@10},
          {name: GCC 11, cc: gcc-11, cxx: g++-11, brew_ver: gcc@11},
          {name: Clang 12, cc: clang, cxx: clang++}
        ]

    env:
      CC: ${{ matrix.compiler.cc }}
      CXX: ${{ matrix.compiler.cxx }}

    steps:
      - name: (Optional) Compiler instalation
        if: ${{ matrix.os == 'macos-12' && startsWith(matrix.compiler.cc, 'gcc') }}
        run: |
          if ! command -v ${{ matrix.compiler.cc }} &> /dev/null
          then
            brew install ${{ matrix.compiler.brew_ver }}
          fi
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - name: CMake configuration
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
      - name: Building
        run: cmake --build build
      - name: Testing
        run: ctest --test-dir build --output-on-failure
